### ISSUE TITLE
Instagram-Scraper doesn't get the biggest picture available anymore

### ISSUE THREAD

**Issue by JuliaTheresa** [rarcega/instagram-scraper#99]
Since a few days it seems Instagram-Scraper only gets smaller pictures and not the best available at Instagram.

I'm getting this file (according to the metadata in the json):
            "standard_resolution": {
                "height": 706, 
                "url": "https://scontent-frx5-1.cdninstagram.com/t51.2885-15/sh0.08/e35/p640x640/21827053_492880454407460_2010165782540976128_n.jpg", 
                "width": 640

which has 706 x 640 (71.0KB)

But there is also this version available
wget https://scontent-frx5-1.cdninstagram.com/t51.2885-15/e35/21827053_492880454407460_2010165782540976128_n.jpg

which has 1193 x 1080 (115.3KB)

I think it started a few days ago and it also happens for older pictures. If I do a run of the same user I'm getting now much smaller pictures although the bigger pictures are still on the server.

Can you please verify and fix this issue? Many thanks from a loyal user

**Comment by rarcega** [comment]
The segments in the image path were modified. If you remove the `p640x640`, portion from the first url you will get the the full size image. 

`https://scontent-frx5-1.cdninstagram.com/t51.2885-15/sh0.08/e35/p640x640/21827053_492880454407460_2010165782540976128_n.jpg`

to

`https://scontent-frx5-1.cdninstagram.com/t51.2885-15/sh0.08/e35/21827053_492880454407460_2010165782540976128_n.jpg`

Fixed in [v1.5.5](https://github.com/rarcega/instagram-scraper/releases/tag/1.5.5)

To upgrade: `pip install instagram-scraper --upgrade`

**Comment by VasiliPupkin256** [comment]
It still throwing this error:
  File "...\lib\runpy.py", line 170, in _run_module_as_main 
	"__main__", mod_spec)
  File "...\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\Scripts\instagram-scraper.exe\__main__.py", line 9, in <module>
  File "...\lib\site-packages\instagram_scraper\app.py", line 710, in main
	scraper.scrape()
  File "...\lib\site-packages\instagram_scraper\app.py", line 329, in scrape
    self.get_media(dst, executor, future_to_item, username)
  File "...\lib\site-packages\instagram_scraper\app.py", line 386, in get_media
    unit=' media', disable=self.quiet):
  File "...\lib\site-packages\tqdm\_tqdm.py", line 905, in __iter__
	for obj in iterable:
  File "...\lib\site-packages\instagram_scraper\app.py", line 431, in media_gen
    media = self.fetch_media_json(username, max_id=None)
  File "...\lib\site-packages\instagram_scraper\app.py", line 461, in fetch_media_json
    media['items'] = [self.augment_media_item(item) for item in media['items']]
  File "...\lib\site-packages\instagram_scraper\app.py", line 461, in <listcomp>
    media['items'] = [self.augment_media_item(item) for item in media['items']]
  File "...\lib\site-packages\instagram_scraper\app.py", line 478, in augment_media_item
    self.get_media_urls(item)
  File "...\lib\site-packages\instagram_scraper\app.py", line 490, in get_media_urls
    url = item[item['type'] + 's']['standard_resolution']['url'].split('?')[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by VasiliPupkin256** [comment]
`e35` can also be stripped from the url. What does it mean?
